apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: online-event-booking-saleha-irum
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-pod
          image: salehaa/user_service:1.0.0  
          ports:
            - containerPort: 8000
          env:
            # ConfigMap values
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: event-booking-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: event-booking-config
                  key: POSTGRES_PORT
            # secrets
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: event-booking-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-booking-secrets
                  key: POSTGRES_PASSWORD
--- 
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: online-event-booking-saleha-irum
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 80   # Exposed service port
      targetPort: 8000  # Container's port
  type: ClusterIP 
